from __future__ import annotations

import csv
from pathlib import Path

from _bootstrap import bootstrap_repo_path

bootstrap_repo_path()

from src.pipeline import load_project_settings


def main() -> None:
    settings = load_project_settings()
    root = Path(settings["root"])
    artifact_rows = _read_csv(root / "results" / "tables" / "tbl1_main_results.csv")
    out_dir = root / "paper" / "usenix_security26"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "artifact_table.tex").write_text(
        _build_artifact_table_tex(artifact_rows),
        encoding="utf-8",
    )
    print(out_dir / "artifact_table.tex")


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _build_artifact_table_tex(artifact_rows: list[dict[str, str]]) -> str:
    explicit = {
        (row["method"], row["architecture"]): row
        for row in artifact_rows
        if row["attack_variant"] == "explicit"
    }
    methods = [
        ("no_recovery", "No recovery"),
        ("root_delete", "Root delete"),
        ("full_reset", "Full reset"),
        ("revoke_no_replay", "Revoke-only"),
        ("coarse_rollback", "Rollback"),
        ("selective_replay", "Selective replay"),
    ]

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/export_latex_tables.py")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{5.5pt}")
    lines.append("\\begin{tabular}{lccc|ccc}")
    lines.append("\\toprule")
    lines.append("& \\multicolumn{3}{c|}{Retrieval memory (explicit)} & \\multicolumn{3}{c}{Summary memory (explicit)}\\\\")
    lines.append("\\cmidrule(lr){2-4}\\cmidrule(l){5-7}")
    lines.append("Method & Residual ASR & S4 retention & Extra calls & Residual ASR & S4 retention & Extra calls\\\\")
    lines.append("\\midrule")
    for key, label in methods:
        retrieval = explicit[(key, "retrieval")]
        summary = explicit[(key, "summary")]
        label_tex = "\\textbf{Selective replay}" if key == "selective_replay" else label
        lines.append(
            f"{label_tex} & "
            f"{_fmt( retrieval['residual_asr_s3'])} & {_fmt(retrieval['s4_retention_accuracy'])} & {_fmt(retrieval['extra_llm_calls_after_detection'])} & "
            f"{_fmt(summary['residual_asr_s3'])} & {_fmt(summary['s4_retention_accuracy'])} & {_fmt(summary['extra_llm_calls_after_detection'])}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\caption{Deterministic artifact results on explicit attacks. Selective replay is the only method that simultaneously reaches zero residual S3 attack success and preserves non-zero S4 retention, while reducing post-detection cost relative to rollback on retrieval memory.}")
    lines.append("\\label{tab:artifact-main}")
    lines.append("\\end{table*}")
    lines.append("")
    return "\n".join(lines) + "\n"


def _fmt(value: str) -> str:
    try:
        numeric = float(value)
    except ValueError:
        return value
    if numeric.is_integer():
        return str(int(numeric))
    return f"{numeric:.3f}".rstrip("0").rstrip(".")


if __name__ == "__main__":
    main()
